# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

gems: [bourbon, neat]

# Site settings
title: FinTech to Go
description: "The fastest way to keep up with FinTech news."
keywords: fintech, news, media
email: tripathi@vesthq.com
url: http://www.fintechtogo.com
repository: https://github.com/fintechtogo
google_analytics: UA-52446115-1
