# General
permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

gems: [bourbon, neat]

# Site settings
title: FinTech to Go
description: "The fastest way to keep up with FinTech news."
email: tripathi@vesthq.com
baseurl: "/fintechtogo" # the subpath of your site, e.g. /blog/
url: http://fintechtogo.com
repository: https://github.com/fintechtogo
google_analytics: UA-52446115-1
